apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    agent: Trump Letter Drafts
    environment: staging
    managed-by: caminu
  name: Trump Letter Drafts-staging
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: staging
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: openai-api-key
        image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/caminu-agents/${PROJECT_ID}/Trump
          Letter Drafts:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
      serviceAccountName: Trump Letter Drafts-sa
